[features]
seeds = false
skip-lint = false
[programs.localnet]
multisig-controller = "F6FgmMhLmtCM8836YHnBKtTLhRMcCa3AcZgcM5wXkTJJ"
nft-reputation = "3mYGDQq3NM4xgJAe3khNsicsnnJwHL6kBpLTATXDiMM9"
org-nft-guard = "8BgW2REXu3HZU8FWNdVHkvdWVTDDgupmhLJk8dc86xA2"
organization = "GaZVotekguK2dubFsnqHs8LFmKGDfRHBQXrwfVEXPa96"
organization_wallet = "5pBYHxaoqyLxcgE62b5SZ3kg7rwHiFPNPRAW6U6UkCsT"
reputation = "E6qW37nUQgCcqWxwjSkpeAfJeW17YzFbdrEtVrGPMExM"
state_controller = "HEMPVSuZruC176FM63mCk8M86Hgxtims5VNGh1d6M8HX"
vote_proxy = "4DXSkEgY4NTApL27cfX2tviysBKPrxWa4W3wAWTb4oGo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/professormint/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # token-metadata
